#!/bin/bash


source afhba-common


walking_bit_test() 
{
	for pat in 0x00000001 0x00000002 0x00000004 0x00000008 \
		   0x00000010 0x00000020 0x00000040 0x00000080 \
		   0x10000000 0x20000000 0x40000000 0x80000000
	do
		set_sys $1 $pat
		echo test $1 write $pat read $(get_sys $1)
	done
}
loc_regs_test() {
	set_sys LOC/0x0018 0x12345678
	get_sys LOC/0x0018
	walking_bit_test LOC/0x0018
}
rem_regs_test() {
	set_sys REM/0x0104 0x12345678
	get_sys REM/0x0104
	walking_bit_test REM/0x0104
}

link_is_up() {
	ASTAT=$(get_sys LOC/0x0084)
	let lane_up="${ASTAT:9}&1"
	echo $lane_up
}
wait_link_up() {
	while [ "$(link_is_up)" = "0" ];do
		echo "waiting for link up status:$(get_sys LOC/0x0084)"
	done
	echo "link is up status:$(get_sys LOC/0x0084)"
}
enable_aurora() {
	set_sys LOC/0x0080 0x80000000
	wait_link_up
	# next : why?
	set_sys REM/0x0104 0x12345678
	# set completer ID	
	get_sys LOC/0x0018
	set_sys REM/0x0118 $(get_sys LOC/0x0018)
	set_sys REM/0x010c 0x00000004
	# just in case the previous run was not cleanly ended
	set_sys REM/0x0204 0x00000010
	set_sys REM/0x0204 0x00000060
}



[ ! -z $TEST ] && loc_regs_test
enable_aurora
[ ! -z $TEST ] && rem_regs_test


