#!/bin/bash


source afhba-common


walking_bit_test() 
{
	for pat in 0x1 0x2 0x4 0x8 0x10 0x20 0x40 0x80 0x100 \
			0x10000000 0x20000000 0x40000000 0x80000000
	do
		set_sys $1 $pat
		echo test $1 write $pat read $(get_sys $1)
	done
}
loc_regs_test() {
	set_sys LOC/0x0018 0x12345678
	get_sys LOC/0x0018
	walking_bit_test LOC/0x0018
}
rem_regs_test() {
	set_sys REM/0x0104 0x12345678
	get_sys REM/0x0104
	walking_bit_test REM/0x0104
}
enable_aurora() {
	set_sys LOC/0x0080 0x80000000
	# next : why?
	set_sys REM/0x0104 0x12345678
	# set completer ID	
	get_sys LOC/0x0018
	set_sys REM/0x0118 $(get_sys LOC/0x0018)
	set_sys REM/0x010c 0x00000004
	# just in case the previous run was not cleanly ended
	set_sys REM/0x0204 0x00000010
	set_sys REM/0x0204 0x00000060
}



[ -z TEST ] && loc_regs_test
enable_aurora
[ -z TEST ] && rem_regs_test

