#!/bin/bash

DN=${1:-0}

~dt100/bin/run-shot-logger &
LOGPID=$!

fan_hi() {
# peripheral fan HI 90%
	ipmitool raw 0x30 0x70 0x66 0x01 0x01 0x60
}
fan_lo() {
# peripheral fan LO 33%
	ipmitool raw 0x30 0x70 0x66 0x01 0x01 0x40
}
trap "fan_lo" SIGINT SIGTERM


echo checking aurora is up ..
grep +LANE_UP /dev/rtm-t.$DN.ctrl/aurora
if [ $? -ne 0 ];then
	echo aurora lane NOT up, quit
	exit 1
fi
export ACQ2106_UUT=$(cat /dev/rtm-t.${DN}.ctrl/acq_ident)

if [ "${ACQ2106_UUT#acq2106_}" = "${ACQ2106}" ]; then
	echo "ERROR: UUT SFP link NOT connected"
	exit 1
else
	echo streaming from UUT $ACQ2106_UUT
fi

export RECYCLE=0 RTM_DEVNUM=$DN OUTROOT=/data/ACQ400DATA/$DN/${ACQ2106_UUT}
mkdir -p ${OUTROOT}
export PUT4KPERFILE=1
fan_hi
./STREAM/rtm-t-stream-disk | pv > /dev/null
fan_lo

kill -9 $LOGPID
