#!/bin/bash

DN=${1:-0}

~dt100/bin/run-shot-logger &
LOGPID=$!

fan_hi() {
# peripheral fan HI 90%
ipmitool raw 0x30 0x70 0x66 0x01 0x01 0x60
}
fan_lo() {
# peripheral fan LO 33%
ipmitool raw 0x30 0x70 0x66 0x01 0x01 0x21
}
trap "fan_lo" SIGINT SIGTERM

mkdir -p /mnt/afhba.$DN
echo checking aurora is up ..
grep +LANE_UP /dev/rtm-t.$DN.ctrl/aurora
if [ $? -ne 0 ];then
	echo aurora lane NOT up, quit
	exit 1
fi
echo stream to /mnt/afhba.$DN 
#export RECYCLE=1 RTM_DEVNUM=$DN OUTROOT=/mnt/afhba.$DN 
export RECYCLE=0 RTM_DEVNUM=$DN OUTROOT=/data/ACQ400DATA
export PUT4KPERFILE=1
fan_hi
./STREAM/rtm-t-stream-disk | pv > /dev/null
fan_lo

kill -9 $LOGPID
