#!/bin/bash
DN=${1:-0}

for DN in 0 1 2 3
do
	if [ -e /dev/rtm-t.$DN.ctrl/acq_ident ]; then
		ID=$(cat /dev/rtm-t.$DN.ctrl/acq_ident)
		if [ "x$ID" != "xacq2106_65535" ]; then
			PORT=$(cat /dev/rtm-t.$DN.ctrl/acq_port)
			echo "$(hostname) $DN $ID $PORT"
		fi
	fi
done


