#!/bin/bash
# llc-test-harness-AI123-AO56
# AI+AO llc 
# CONTROLS
# LLC_TRG=ext
# LLC_CLK=ext
# AISITES=1,2,3
# AOSITES=5,6
# XOCOMMS=A

[ -d scripts ] && cd scripts

source afhba-common
# site definitions SC: system controller, CB: commsB, AI: AI, AO : AO
SC=0
CA=13
CB=12


# MUST set remote ip-address
REMIP=${1:-acq2106_003}
USER_PROMPT=${USER_PROMPT:-y}		# y forces break between init and run
INTCLKDIV=${INTCLKDIV:-10000}		# 100M/100 = 100kHz
EXTCLKDIV=${EXTCLKDIV:-10}		# 1M/10 = 100kHz

LLC_CLK=${LLC_CLK:-ext}
# default auto SOFT_TRIGGER=0, in transient mode, script will terminate...
# next run the CONTROL PROGRAM
# THEN trigger (eg ext trigger, or run soft_trigger command on box
SOFT_TRIGGER=${SOFT_TRIGGER:-0}

# default transient mode, set # samples.  "no": run continuous mode
TRANSIENT=${TRANSIENT:-2000000}


AISITES=${AISITES:-1,2,3}
# pick off the first AI site as M
AI=${AISITES%,*}


AOSITES=${AOSITES:-5,6}
# pick off the first AO site as M.
AO=${AOSITES%,*}

# DO assume ALL OUTPUTS. 
DOSITES=${DOSITES:-""}
DO="${DOSITES/,/ }"

# route AI data to both CA and CB
CA_SITES=${AISITES}
CB_SITES=${AISITES}

XO_COMMS=${XO_COMMS:-A}

NSPAD=16

XISITES=$AISITES
XOSITES=$AOSITES
PAD=0

init_comms() {	
	cx=$1
	sites=$2

	remote_cmd $cx RESET_CTR=1	
	remote_cmd $cx spad=1
	remote_cmd $cx aggregator sites=$sites
}


init_2106() {
	if [ "$LLC_TRG" = "ext" ]; then
		remote_cmd $AI trg=1,0,1
	else
		remote_cmd $AI trg=1,1,1
	fi
	if [ "$LLC_CLK" = "ext" ]; then
		# route he clock from FP to CLK.d0
		remote_cmd $SC SYS:CLK:FPMUX=FPCLK
		remote_cmd $SC SYS:CLK:BYPASS=1
		remote_cmd $SC SYS:CLK:OE_CLK1_ZYNQ=1
		remote_cmd $SC SIG:SRC:CLK:1=MCLK
		# select CLK.d0
		remote_cmd $AI clk=1,1,1
		remote_cmd $AI CLKDIV=$EXTCLKDIV
		echo setting external clock / $EXTCLKDIV
	else
		remote_cmd $AI clk=0,0,0
		remote_cmd $AI CLKDIV=$INTCLKDIV
		echo setting internal clock / $INTCLKDIV
	fi
	
	
	if [ "x$DOSITES" != "x" ]; then
#		if [ "x$XISITES" != "x" ]; then
#			XISITES=$XISITES,$DOSITES
#		else
#			XISITES=$DOSITES
#		fi
		if [ "x$XOSITES" != "x" ]; then
			XOSITES=$XOSITES,$DOSITES
		else
			XOSITES=$DOSITES
		fi
		PAD=16		
		for dox in $DO; do
			remote_cmd $dox clkdiv 1
			remote_cmd $dox lotide 256
			remote_cmd $dox byte_is_output 1,1,1,1
			remote_cmd $dox mode 1
			# slave AO on AI site 1 master clock
			remote_cmd $dox clk=1,2,1
			remote_cmd $dox clkdiv=1 
			let NSPAD=$NSPAD-1
			let PAD=$PAD-1
		done
	fi
	remote_cmd $SC distributor sites=$XOSITES pad=$PAD comms=$XO_COMMS on
	remote_cmd $AO lotide 256
	# slave AO on AI site 1 master clock
	remote_cmd $AO clk=1,2,1
	remote_cmd $AO clkdiv=1 
	

	# scratchpad, include TLATCH at 0, pad to 64 bytes
	remote_cmd $SC spad=1,$NSPAD,0	
	remote_cmd $SC run0 $XISITES
	
	init_comms $CA $CA_SITES
	init_comms $CB $CB_SITES
}

start_stream() {
        if [ "x$TRANSIENT" = "xno" ]; then
		echo "start stream"
                remote_cmd $SC streamtonowhered start
                echo now view data perhaps using ./mapsample
                echo CTRL-C to quit
                trap "cleanup" SIGINT SIGTERM

                sleep 99999
	else
		echo "start transient"
                if [ $TRANSIENT -gt 1000 ]; then
                        POST=$TRANSIENT
                else
                        POST=100000
                fi
                remote_cmd $SC transient POST=$POST SOFT_TRIGGER=$SOFT_TRIGGER
                remote_cmd $SC set_arm
        fi
}

cleanup() {
	remote_cmd $SC streamtonowhered stop
}

user_prompt() {
	stuff=x
	while [ "$stuff" != "y" ]; do
        	echo "y: run the shot, n: abort"
	        read stuff
		if [ "$stuff" = "n" ]; then
			echo n entered: QUIT without running shot
			exit 0
		fi
	done
}

init_2106
[ "$USER_PROMPT" = "y" ] && user_prompt
start_stream

