#!/bin/bash
# llc-test-harness-intclk-AI1-AO4-zcopy
# AI+AO llc with zerocopy on one fiber. Basic LLC test

[ -d scripts ] && cd scripts

# MUST set remote ip-address
REMIP=${1:-acq2106_003}
INTCLKDIV=${INTCLKDIV:-10000}		# 100M/100 = 100kHz
EXTCLKDIV=${EXTCLKDIV:-10}		# 1M/10 = 100kHz


source afhba-common
# site definitions SC: system controller, CB: commsB, AI: AI, AO : AO
SC=0
CA=13
CB=12
# MASTER AI site
AI=1
# MASTER AO site
AO=5

AOSITES=${AOSITES:-5,6}
AISITES=${AISITES:-1,2,3}

CA_SITES=${AISITES}
CB_SITES=${AISITES}

# DC : Distributor from Comms = 2 : pull from comms A
DC=2
# TODO, this is better:
# DC=A

init_comms() {	
	cx=$1
	sites=$2
	
	remote_cmd $cx spad=1
	remote_cmd $cx aggregator sites=$sites
}


init_2106() {
	if [ "$LLC_TRG" = "ext" ]; then
		remote_cmd $AI trg=1,2,1
	else
		remote_cmd $AI trg=1,1,1
	fi
	if [ "$LLC_CLK" = "ext" ]; then
		remote_cmd $AI clk=1,2,1
		remote_cmd $AI clkdiv=$EXTCLKDIV
		echo setting external clock / $EXTCLKDIV
	else
		remote_cmd $AI clk=0,0,0
		remote_cmd $AI clkdiv=$INTCLKDIV
		echo setting internal clock / $INTCLKDIV
	fi
	remote_cmd $SC distributor sites=$AOSITES comms=$DC on
	remote_cmd $AO lotide 256
	remote_cmd $AO clk=1,2,1
	remote_cmd $AO clkdiv=1 

	remote_cmd $SC spad=1,16,0	
	remote_cmd $SC run0 $AISITES
	
	init_comms $CA $CA_SITES
	init_comms $CB $CB_SITES
}

start_stream() {
	remote_cmd $SC streamtonowhered start
}


cleanup() {
	remote_cmd $SC streamtonowhered stop
}

init_2106
start_stream
echo now view data perhaps using ./mapsample
echo CTRL-C to quit
trap "cleanup" SIGINT SIGTERM

sleep 99999

