#!/bin/bash
# llc-test-harness: configure and start an llc process
#!/bin/bash

# MUST set remote ip-address
REMIP=${1:-10.12.196.129}
STREAMPID=0

source afhba-common

remote_cmd() {
	SITE=$1;shift
	echo $* | nc $REMIP 422$SITE
}

start_dma() { 
	PA=$(get_sys BUF/pa)
	echo buffer PA $PA
	set_sys REM/0x0204 0x60
	get_sys REM/0x0204
	set_sys REM/0x0240 $PA
	get_sys REM/0x0240
	set_sys REM/0x0204 0x61	 					
}

stop_dma() {
	set_sys REM/0x0204 0x60
	set_sys REM/0x0204 0x10
	set_sys REM/0x0204 0x60
}

init_706() {
	remote_cmd 1 trg=1,2,1
	remote_cmd 0 spad=1,7,0	
	remote_cmd 0 run0 1
}

start_stream() {
	remote_cmd 0 streamtonowhered start
}


cleanup() {
#	kill ${STREAMPID}
	stop_dma
	remote_cmd 0 streamtonowhered stop
}

stop_dma
start_dma
init_706
start_stream
echo now view data perhaps using ./mapsample
echo CTRL-C to quit
trap "cleanup" SIGINT SIGTERM

sleep 99999

