#!/bin/bash
# llc-test-harness: configure and start an llc process
#!/bin/bash

[ -d scripts ] && cd scripts

# MUST set remote ip-address
REMIP=${1:-acq2106_004}
INTCLKDIV=${INTCLKDIV:-100}		# 100M/100 = 1MHz
EXTCLKDIV=${EXTCLKDIV:-1}		# 1M/1 = 1MHz
STREAMPID=0

source afhba-common
# site definitions SC: system controller, CX: commsA, AI: AI
SC=0
CX=${CX:-13}
AI=1

# optional COMMS=A, COMMS=B arg works as well.
case $COMMS in
A)	CX=13;;
B)	CX=12;;
esac

init_comms() {
	remote_cmd $CX aggregator sites=1
	remote_cmd $CX spad=1
}
init_acq2106A() {
	if [ "$LLC_TRG" = "ext" ]; then
		remote_cmd $AI trg=1,2,1
	else
		remote_cmd $AI trg=1,1,1
	fi
	if [ "$LLC_CLK" = "ext" ]; then
		remote_cmd $AI clk=1,2,1
		remote_cmd $AI clkdiv=$EXTCLKDIV
		echo setting external clock / $EXTCLKDIV
	else
		remote_cmd $AI clk=0,0,0
		remote_cmd $AI clkdiv=$INTCLKDIV
		echo setting internal clock / $INTCLKDIV
	fi
	remote_cmd $SC spad=1,8,0	
	remote_cmd $SC run0 1
}

start_stream() {
	remote_cmd $SC streamtonowhered start
}


cleanup() {
	remote_cmd $SC streamtonowhered stop
}

if [ "x$COMMS_ONLY" = "xYES" ]; then
	init_comms
	exit 0
fi
init_acq2106A
start_stream
echo CTRL-C to quit
trap "cleanup" SIGINT SIGTERM

sleep 99999

