#!/bin/bash
# llc-test-harness-extclk-AI1234-AO12
# AI+AO llc on two fibers AI and AO in separate boxes AI on Comms A and AO on Comms B. Basic LLC test

[ -d scripts ] && cd scripts

# MUST set remote ip-address
INBOX=${1:-acq2106_076}
OUTBOX=${1:-acq2106_079}
EXTCLKDIV=${EXTCLKDIV:-10}		# 1M/10 = 100kHz
STREAMPID=0


source afhba-common
# site definitions SC: system controller, CB: commsB, AI: AI, AO : AO
SC=0
CA=13
CB=12
AI=1
AO=1

AISITES=1,2,3,4,5,6
AOSITES=1,2


in_cmd() {
        REMIP=$INBOX remote_cmd $*
}

out_cmd() {
        REMIP=$OUTBOX remote_cmd $*
}


init_2106() {
	echo CLK TRG basics have been preset, but
	echo settting clkdiv=$EXTCLKDIV
	in_cmd $AI clkdiv=$EXTCLKDIV
	out_cmd $AO clkdiv=$EXTCLKDIV
	out_cmd $AO lotide 256


	in_cmd $SC spad=1,16,0	
	in_cmd $CA spad 1
	in_cmd $CA aggregator sites=$AISITES

	out_cmd $SC distributor sites=$AOSITES comms=2 pad=0 on
	
}

start_stream() {
	in_cmd $SC streamtonowhered start
}


cleanup() {
#	kill ${STREAMPID}
	in_cmd $SC streamtonowhered stop
}

init_2106
start_stream
echo now view data perhaps using ./mapsample
echo CTRL-C to quit
trap "cleanup" SIGINT SIGTERM

sleep 99999

