#!/bin/bash
# file PROJECTS/AFHBA404/scripts/llc-run-full-auto-thomson
# POST is number of samples in LLC control loop
# TLEN is the transient capture, overrun to make sure LLC terminates
POST=${POST:-1000}
DELAY=${DELAY:-10}
BUFLEN=${BUFLEN:-4096}
DEMUX=${DEMUX:-1}
let TLEN="$POST*120/100"

CTRL_PROG=${CTRL_PROG:-"acqproc"}
HAPIDIR=/home/dt100/PROJECTS/acq400_hapi
AFHBA404DIR=/home/dt100/PROJECTS/AFHBA404
LLCDIR=${AFHBA404DIR}/LLCONTROL
ACQPROC_CONFIG=${ACQPROC_CONFIG:-"ACQPROC/configs/thomson1344.json"}
UUTS=$(python3 $AFHBA404DIR/scripts/list_capture_uuts.py --json_file=${AFHBA404DIR=/home/dt100/PROJECTS/AFHBA404}/$ACQPROC_CONFIG)
EXT_UCLK=${EXT_UCLK:-"0"}

export LD_LIBRARY_PATH=/usr/local/mdsplus/lib64/

export EXTCLKDIV=${EXTCLKDIV:-10}

set_clocks() {
	echo \
	EXT_UCLK=$EXT_UCLK SIMULATE=0 $AFHBA404DIR/HAPI/thomson_config_sampleondemand.py --delay=$DELAY $UUTS
	EXT_UCLK=$EXT_UCLK SIMULATE=0 $AFHBA404DIR/HAPI/thomson_config_sampleondemand.py --delay=$DELAY $UUTS
}


acqproc() {
	cd $AFHBA404DIR
	cat - > control_program.env <<EOF
	export DEVMAX=$DEVMAX
	export VERBOSE=$VERBOSE
	export HW=1
	export HW_MULTI=1
	export RTPRIO=10
	export AFFINITY=$AFFINITY
	export SINGLE_THREAD_CONTROL=control_dup1
EOF
        sudo bash -c 'source control_program.env; ./ACQPROC/acqproc '${ACQPROC_CONFIG}' '$POST''
}


control_program() {
	cd $LLCDIR
	export AICHAN=192
	export SPADLONGS=16
# isolcpus=4,5,6,7,8...
# taskset 0x10 means "run on processor 4"
	export TASKSET="taskset 0x8"
	[ "x$TASKSET" != "x" ] && echo TASKSET $TASKSET
	$TASKSET ./afhba-llcontrol-multiuut $1 &
	echo wait for llcontrol, PID $CTRLPID
	wait
	echo CONTROL PROGRAM 99
}

control_script() {
	echo control_script       
       	echo "$HAPIDIR/user_apps/acq400/acq400_capture.py $UUTS" 
        SITECLIENT_TRACE=0 STATUSMONITOR_TRACE=1 python3 $HAPIDIR/user_apps/acq400/acq400_capture.py \
		--transient="PRE=0 POST=$TLEN SOFT_TRIGGER=0 DEMUX=$DEMUX" --soft_trigger=0 \
		$UUTS
	echo control_script over
}



case "x$1" in
xset_clocks)
	set_clocks;;
xcontrol_program)
	shift
	control_program $*;;
xcontrol_script)
	control_script;;
*)
	echo llc-run-full-auto-thomson $UUTS POST=$POST TLEN=$TLEN DELAY=$DELAY | tee $LLCDIR/llc-run-full-auto-thomson.txt

	set_clocks
	echo sudo $0 control_program $POST

	if [ "$CTRL_PROG" = "original" ]; then
		sudo $0 control_program $POST &
	else
		acqproc &
	fi

	control_script
	wait
	echo wait complete
	(cd PROJECTS/AFHBA404; sudo ./scripts/get_latstats)
	;;
esac
