#!/bin/bash

DDB=/sys/kernel/debug/dynamic_debug
[ -d $DDB ] || mount -t debugfs debug /sys/kernel/debug/
echo 9 > /proc/sys/kernel/printk
#echo file afhba_stream_drv.c +p >$DDB/control


#/sbin/insmod afhba.ko ll_mode_only=0 reg_access_verbose=0 aurora_monitor=1
/sbin/insmod afhba.ko ll_mode_only=0 reg_access_verbose=0 aurora_monitor=0 nbuffers=64 eot_interrupt=0 WORK_TO=1

#echo file afhba_stream_drv.c +p >$DDB/control

if [ "$1" = "full" ]; then
/sbin/insmod afhbasfp.ko  
/sbin/insmod spi-bitbang.ko 
/sbin/insmod mtd.ko 
/sbin/insmod m25p80.ko
/sbin/insmod afhbaspi.ko
fi
