#!/bin/bash
M1=7
M2=3


manual() {
	echo "playing $(cat /dev/shm/amx_ao_map)"
	echo "say when"; read stuff
	[ "$stuff" = "q" ] && exit 0
}
auto() {
	usleep 20000
}

TEMPO=${TEMPO:-auto}
set() {
	echo $* > /dev/shm/amx_ao_map
	$TEMPO
}



while [ 1 ]; do
	set $M1,1
	set $M2,1
	set $M1,1 $M2,1
done
