#!/bin/bash

DN=${1:-0}
# runs mir1-stream-to-flash in a window

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

HN=$(/home/dt100/bin/get-ident $DN | awk '{ print $3 }')

cd /home/dt100/PROJECTS/AFHBA404

#mate-terminal --title="mir-stream-to-flash $DN" \
#    -e "./scripts/mir1-stream-to-flash $DN" &

unbuffer ./scripts/mir1-stream-to-flash $DN > /tmp/$HN.hts &
