#!/bin/bash

DN=${1:-0}
NB=${2:-1024}
RCL=${3:-1}

mkdir -p /mnt/afhba.$DN -m 0777
echo checking aurora is up ..
grep +LANE_UP /dev/rtm-t.${DN}.ctrl/aurora
if [ $? -ne 0 ];then
	echo aurora lane NOT up, quit
	exit 1
fi
outroot=/mnt/afhba.$DN/$(cat /dev/rtm-t.${DN}.ctrl/acq_ident)
mkdir -p $outroot -m 0777
echo stream to $outroot
RECYCLE=$RCL CONCAT=0 NBUFS=$NB RTM_DEVNUM=$DN OUTROOT=$outroot  ./STREAM/rtm-t-stream-disk

