#!/bin/bash

DN=${1:-0}
PATH=$PATH:/usr/local/bin

HBFARM=${HBFARM:-1 2}
# alt: HBFARM=1 for single source module

echo checking aurora is up ..
grep +LANE_UP /dev/rtm-t.$DN.ctrl/aurora
if [ $? -ne 0 ];then
	echo aurora lane NOT up, quit
	exit 1
fi
echo stream to /mnt/afhba.$DN 
mkdir -p /mnt/afhba.$DN
export HBFARM_SITELW=4
export HBFARM_PROCESS=checkramp480
export HBFARM_VERBOSE=0
export NAMES_ON_STDIN=1

RTM_DEVNUM=$DN RECYCLE=1 OUTROOT=/mnt/afhba.$DN ./STREAM/rtm-t-stream-disk| \
	hbfarm $HBFARM
