#!/bin/bash

DN=${1:-0}

mkdir -p /mnt/afhba.$DN
echo checking aurora is up ..
grep +LANE_UP /dev/rtm-t.$DN.ctrl/aurora
if [ $? -ne 0 ];then
	echo aurora lane NOT up, quit
	exit 1
fi
echo stream to /mnt/afhba.$DN 
RECYCLE=1 RTM_DEVNUM=$DN OUTROOT=/mnt/afhba.$DN ./STREAM/rtm-t-stream-disk

