#!/bin/bash

DN=${1:-0}
NB=${2:-1024}

mkdir -p /mnt/afhba.$DN
echo checking aurora is up ..
grep +LANE_UP /dev/rtm-t.0.ctrl/aurora
if [ $? -ne 0 ];then
	echo aurora lane NOT up, quit
	exit 1
fi
echo stream to /mnt/afhba.$DN 
NBUFS=$NB RTM_DEVNUM=$DN OUTROOT=/mnt/afhba.$DN ./STREAM/rtm-t-stream-disk

