#!/bin/sh
DEV=${1:-0}
SKIP=${2:-0}
BS=${3:-4096}
[ $SKIP -ne 0 ] && echo Starts at +$((SKIP*BS))
./mmap -f /dev/rtm-t.${DEV}.data/hb00 | dd bs=${BS} skip=${SKIP} count=2 status=none | hexdump | head

