
CXXFLAGS=-O2 -std=c++11 -fopenmp -lpopt


all: hbfarm425 checkramp checkramp480 multisitecheckramp

clean:
	rm -f hbfarm425 checkramp


myinstall:
	cp hbfarm425 checkramp checkramp480 multisitecheckramp ~/bin

install:
	cp hbfarm425 checkramp /usr/local/bin
	
